name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  PRESENTATIONS: '["basics", "advanced"]'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presentation: ${{ fromJson(env.PRESENTATIONS) }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: pnpm
      - name: Install dependencies
        run: |
          npm i -g @antfu/ni
          nci
      - name: Build presentation
        run: nr build --base /${{ matrix.presentation }}/ --out dist/${{ matrix.presentation }}/ ${{ matrix.presentation }}.md
      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: slidev-${{ matrix.presentation }}
          path: dist/${{ matrix.presentation }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6

      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts
          pattern: slidev-*
          merge-multiple: false

      - name: Prepare final dist and index
        run: |
          mkdir -p final-dist
          # Move folders to final structure
          for dir in artifacts/slidev-*; do
            name=${dir#artifacts/slidev-}
            mv "$dir" "final-dist/$name"
          done
          
          # Convert JSON array to space-separated arguments for the script
          NAMES=$(echo '${{ env.PRESENTATIONS }}' | jq -r '.[]')
          chmod +x generate-index.sh
          ./generate-index.sh $NAMES

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v4
        with:
          path: final-dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
